name: build-and-publish

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment:
      name: DEV
    permissions:
      id-token: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install build
      - name: Lint with flake8
        run: |
          flake8 ctrf --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Install plugin and run tests
        run: |
          pip install pytest-xdist
          pip install .
          python -m pytest --ctrf $REPORT tests/test_plugin.py
        env:
            REPORT: 'test-results/report.json'
      - name: Build package
        run: |
          python -m build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Generate Pretty Report
        if: always()
        run: |
          npx github-actions-ctrf test-results/report.json